version: '3'

services:
  frontend:
    container_name: wegCase
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /node_modules

  graphql-faker:
    container_name: graphql-Faker
    image: apisguru/graphql-faker
    ports:
      - "9002:9002"
    volumes:
      - ./src/schema:/schema
    command: /schema/schema.faker.graphql

  # NGINX SERVICE #
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2G'
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
