import type {Metadata} from "next";
import {NextUIProvider} from "@nextui-org/react";
import "./globals.css";
import {EmployeeProvider} from "@/Provider/context";
import Sidebar from "@/components/Sidebar";
import React from "react";

export const metadata: Metadata = {
    title: "En Uygun Çalışan Paneli",
    description: "Generated by create next app",
};
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <NextUIProvider>
            <EmployeeProvider>
                <div className={` bg-[#F7FAFC] flex w-full  h-auto`}>
                    <Sidebar/>
                    <div className="w-full ">
                        {children}
                    </div>
                </div>
            </EmployeeProvider>
        </NextUIProvider>
        </body>


        </html>
    );
}
